In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras

2025-04-08 00:36:34.376447: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
x_train = df.drop(labels=['PassengerId', 'Survived', 'Name', 'Ticket', 'Cabin'], axis=1)
y_train = df['Survived']

In [8]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       714 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Fare      891 non-null    float64
 6   Embarked  889 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [9]:
x_train = pd.get_dummies(x_train, columns=["Sex", "Embarked"], drop_first=True)

In [10]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Pclass      891 non-null    int64  
 1   Age         714 non-null    float64
 2   SibSp       891 non-null    int64  
 3   Parch       891 non-null    int64  
 4   Fare        891 non-null    float64
 5   Sex_male    891 non-null    bool   
 6   Embarked_Q  891 non-null    bool   
 7   Embarked_S  891 non-null    bool   
dtypes: bool(3), float64(2), int64(3)
memory usage: 37.5 KB


In [11]:
x_train.head()

Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0       3  22.0      1      0   7.2500      True       False        True
1       1  38.0      1      0  71.2833     False       False       False
2       3  26.0      0      0   7.9250     False       False        True
3       1  35.0      1      0  53.1000     False       False        True
4       3  35.0      0      0   8.0500      True       False        True

In [12]:
x_train = (x_train - x_train.mean()) / x_train.std()


In [13]:
x_train.head()

Pclass       Age     SibSp     Parch      Fare  Sex_male  Embarked_Q  \
0  0.826913 -0.530005  0.432550 -0.473408 -0.502163  0.737281    -0.30739   
1 -1.565228  0.571430  0.432550 -0.473408  0.786404 -1.354813    -0.30739   
2  0.826913 -0.254646 -0.474279 -0.473408 -0.488580 -1.354813    -0.30739   
3 -1.565228  0.364911  0.432550 -0.473408  0.420494 -1.354813    -0.30739   
4  0.826913  0.364911 -0.474279 -0.473408 -0.486064  0.737281    -0.30739   

   Embarked_S  
0    0.618959  
1   -1.613803  
2    0.618959  
3    0.618959  
4    0.618959

In [14]:
x_train = x_train.fillna(x_train.median())


In [15]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Pclass      891 non-null    float64
 1   Age         891 non-null    float64
 2   SibSp       891 non-null    float64
 3   Parch       891 non-null    float64
 4   Fare        891 non-null    float64
 5   Sex_male    891 non-null    float64
 6   Embarked_Q  891 non-null    float64
 7   Embarked_S  891 non-null    float64
dtypes: float64(8)
memory usage: 55.8 KB


In [16]:
x_train = np.array(x_train).astype(np.float32)

In [17]:
y_train = np.array(y_train).astype(np.float32)

In [18]:
x_train[0]

array([ 0.8269128 , -0.5300051 ,  0.43255043, -0.47340772, -0.5021631 ,
        0.737281  , -0.3073897 ,  0.6189587 ], dtype=float32)

In [19]:
y_train[0]

0.0

In [20]:
len(x_train)

891

In [21]:
len(y_train)

891

In [22]:
from keras import layers

In [32]:
model = keras.Sequential([
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # binary classification
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=4, batch_size=16)


Epoch 1/4
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5828 - loss: 0.6680
Epoch 2/4
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7709 - loss: 0.5352
Epoch 3/4
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8088 - loss: 0.4693
Epoch 4/4
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8152 - loss: 0.4391


In [39]:
test_df = pd.read_csv('test.csv')

In [40]:
x_test = test_df.drop(labels=['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [43]:
x_test.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [45]:
x_test = pd.get_dummies(x_test, columns=["Sex", "Embarked"], drop_first=True)

In [46]:
x_test = (x_test - x_test.mean()) / x_test.std()

In [47]:
x_test.head()

Pclass       Age     SibSp     Parch      Fare  Sex_male  Embarked_Q  \
0  0.872436  0.298099 -0.498872 -0.399769 -0.497213  0.755024    2.840354   
1  0.872436  1.179547  0.616254 -0.399769 -0.512045 -1.321292   -0.351227   
2 -0.315441  2.237285 -0.498872 -0.399769 -0.463974  0.755024    2.840354   
3  0.872436 -0.230769 -0.498872 -0.399769 -0.482308  0.755024   -0.351227   
4  0.872436 -0.583349  0.616254  0.619154 -0.417469 -1.321292   -0.351227   

   Embarked_S  
0   -1.349059  
1    0.739484  
2   -1.349059  
3    0.739484  
4    0.739484

In [48]:
x_test = x_test.fillna(x_test.median())

In [49]:
x_test = np.array(x_test).astype(np.float32)

In [50]:
predictions = model.predict(x_test)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


In [52]:
predictions[:10]

array([[0.12922569],
       [0.40829653],
       [0.13505039],
       [0.11533517],
       [0.49570784],
       [0.16750903],
       [0.6586934 ],
       [0.2438643 ],
       [0.60433763],
       [0.07514452]], dtype=float32)

In [53]:
predictions.shape

(418, 1)

In [57]:
predictions.reshape((418,))

array([0.12922569, 0.40829653, 0.13505039, 0.11533517, 0.49570784,
       0.16750903, 0.6586934 , 0.2438643 , 0.60433763, 0.07514452,
       0.11481605, 0.27568933, 0.87544936, 0.09240532, 0.8576227 ,
       0.7409027 , 0.27941597, 0.1999912 , 0.4726729 , 0.5143293 ,
       0.29708052, 0.25684738, 0.8528174 , 0.6227221 , 0.8992179 ,
       0.0542402 , 0.88613373, 0.19266385, 0.31888285, 0.10552415,
       0.11486308, 0.15530418, 0.4287009 , 0.4600333 , 0.4430805 ,
       0.21035533, 0.50628346, 0.5191669 , 0.12257399, 0.16779733,
       0.17563966, 0.38737586, 0.07850602, 0.7166167 , 0.8532066 ,
       0.12146638, 0.3571517 , 0.15925123, 0.8478377 , 0.4823972 ,
       0.44635582, 0.29666921, 0.6415174 , 0.86580664, 0.29744682,
       0.07117075, 0.09215485, 0.12127385, 0.09458432, 0.9384153 ,
       0.1544532 , 0.17567405, 0.15037547, 0.68214375, 0.6885274 ,
       0.733747  , 0.6934798 , 0.3079402 , 0.4508266 , 0.8345272 ,
       0.6764316 , 0.13671651, 0.50432444, 0.46617806, 0.93244

In [59]:
predictions.shape

(418, 1)

In [61]:
prediction_labels = (predictions > 0.5).astype(int)

In [62]:
prediction_labels[:10]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0]])

In [63]:
len(prediction_labels)

418

In [65]:
submission_df = pd.DataFrame({
    'PassengerId': test_df['PassengerId'],
    'Survived': prediction_labels.flatten()
})
submission_df.head()
submission_df.to_csv('submission.csv', index=False)